<?php

/**
 * The harness's composer.json and phpunit.xml: this core from its checkout,
 * each provider from a checkout under /omnitrade/plugins when there is one,
 * from GitHub (branch 1.x) otherwise; every package's tests in one run.
 * Files are rewritten only when they change, so the entrypoint knows when
 * to install.
 */
$plugins = require __DIR__.'/plugins.php';
$core = '/omnitrade/core';
$local = '/omnitrade/plugins';
$out = '/harness';

$repositories = [['type' => 'path', 'url' => $core, 'options' => ['symlink' => true, 'versions' => ['glitchr/omnitrade' => '1.x-dev']]]];
$require = ['glitchr/omnitrade' => '1.x-dev'];
$tests = ['Omnitrade\\Tests\\' => "$core/Tests/"];
$suites = ['core' => "$core/Tests"];
$sources = [];
foreach ($plugins as $slug => [$testsNs]) {
    $name = "omnitrade/$slug";
    $dir = "$local/$slug";
    $meta = is_file("$dir/composer.json") ? json_decode((string) file_get_contents("$dir/composer.json"), true) : null;
    if (($meta['name'] ?? null) === $name) {
        $repositories[] = ['type' => 'path', 'url' => $dir, 'options' => ['symlink' => true, 'versions' => [$name => '1.x-dev']]];
        $testDir = "$dir/Tests";
        $sources[$slug] = 'checkout';
    } else {
        $repositories[] = ['type' => 'vcs', 'url' => "https://github.com/glitchr-studio/omnitrade-$slug.git"];
        $testDir = "$out/vendor/omnitrade/$slug/Tests";
        $sources[$slug] = 'github';
    }
    $require[$name] = '1.x-dev';
    $tests[$testsNs] = $testDir.'/';
    $suites[$slug] = $testDir;
}

$composer = [
    'name' => 'glitchr/omnitrade-harness',
    'description' => 'glitchr/omnitrade with every provider: generated by docker/harness/setup.php, do not edit.',
    'type' => 'project',
    'license' => 'MIT',
    'repositories' => $repositories,
    'require' => $require + [
        'php' => '>=8.2',
        'symfony/console' => '^7.0|^8.0',
        'symfony/http-client' => '^7.0|^8.0',
        'symfony/var-dumper' => '^7.0|^8.0',
    ],
    'require-dev' => [
        'phpunit/phpunit' => '^11.0',
        'symfony/config' => '^7.0|^8.0',
        'symfony/dependency-injection' => '^7.0|^8.0',
        'symfony/http-kernel' => '^7.0|^8.0',
    ],
    'autoload' => ['psr-4' => ['Omnitrade\\Harness\\' => "$core/docker/harness/src/"]],
    'autoload-dev' => ['psr-4' => $tests],
    'minimum-stability' => 'dev',
    'prefer-stable' => true,
    'config' => ['sort-packages' => true, 'allow-plugins' => ['php-http/discovery' => true]],
];
$json = json_encode($composer, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES)."\n";
if (!is_file("$out/composer.json") || file_get_contents("$out/composer.json") !== $json) {
    file_put_contents("$out/composer.json", $json);
    echo "composer.json composed: ", implode(', ', array_map(static fn ($s, $f) => "$s ($f)", array_keys($sources), $sources)), "\n";
}

$xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<phpunit xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"vendor/phpunit/phpunit/phpunit.xsd\" bootstrap=\"vendor/autoload.php\" colors=\"true\" failOnWarning=\"true\" cacheDirectory=\".phpunit.cache\">\n    <testsuites>\n";
foreach ($suites as $suite => $dir) {
    $xml .= "        <testsuite name=\"$suite\"><directory>$dir</directory></testsuite>\n";
}
$xml .= "    </testsuites>\n</phpunit>\n";
if (!is_file("$out/phpunit.xml") || file_get_contents("$out/phpunit.xml") !== $xml) {
    file_put_contents("$out/phpunit.xml", $xml);
}
